POST http://localhost:9001/teams/
Content-Type: application/json

{
    "name": "Los Angeles Angels of Anaheim",
    "alternate": "California Angels",
    "abbreviation": "LAA",
    "organization": "Major League Baseball",
    "league": "American League",
    "division": "AL West"
}
