POST http://localhost:9001/teams/
Content-Type: application/json

{
    "name": "Yomiuri Giants",
    "abbreviation": "巨",
    "organization": "Nippon Professional Baseball",
    "league": "Central League"
}
