# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs,
# ran sequentially or in parallel
jobs:
  # Deploy on pull requests,
  # unless the commit message contains #skip
  deploy:
    if: |
      github.event_name == 'push'
      && !contains(github.event.commits[0].message, '#skip')
    
    runs-on: ubuntu-18.04

    steps:
      - name: Deployment start time
        run: |
          echo Deployment started
          date

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: Deploy to heroku #
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: take-me-out-to-the-ballgame
          heroku_email: banaanihillo@protonmail.ch
          healthcheck: |
            https://take-me-out-to-the-ballgame.herokuapp.com/healthcheck
          checkstring: Okay
          rollbackonhealthcheckfailed: true
      
      - name: Time after deployment
        uses: gerred/current-time@v1.0.0
        id: time-after-deployment

      - name: Bump the version tag on success
        if: ${{success()}}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
      
      - name: Print date after successful deployment
        if: ${{success()}}
        run: |
          echo Deployment done
          date
      
      - name: Notify in case of a failure
        if: ${{failure()}}
        #uses: appleboy/telegram-action@v0.1.1
        env:
          TIME: ${{steps.time-after-deployment.outputs.time}}
        run: echo "$TIME"
        #with:
          #to: ${{secrets.TELEGRAM_TO}}
          #token: ${{secrets.TELEGRAM_TOKEN}}
          #message: |
            #${{github.event_name}} deployment failed
            #at ${{env.TIME}}
#
  lint:
    runs-on: ubuntu-18.04

    steps: #
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: npm install
        run: npm install
      
      - name: lint
        run: npm run eslint
      
