# This is a basic workflow to help you get started with Actions

name: CI/CD pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs,
# ran sequentially or in parallel
jobs:
  print_date:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a <em> sequence </em> of tasks
    steps:
      - name: Pipeline start time
        run: |
          echo First step of pipeline started
          date
  
  deploy:
    if: |
      github.event_name == 'push'
      && !contains(github.event.commits[0].message, '#skip')
    
    runs-on: ubuntu-18.04

    steps:
      - name: Deployment start time
        run: |
          echo Deployment started
          date

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: take-me-out-to-the-ballgame
          heroku_email: banaanihillo@protonmail.ch
          healthcheck: |
            http://take-me-out-to-the-ballgame.herokuapp.com/healthcheck
          checkstring: OK
          rollbackonhealthcheckfailed: true
      
      
      - name: Print date after successful deployment
        if: ${{success()}}
        run: |
          echo Deployment done
          date
      
      - name: Notify in case of a failure
        if: ${{failure()}}
        run: |
          echo Deployment failed
          date
        #uses: appleboy/telegram-action@v0.1.1
        #with:
          #to: ${{secrets.TELEGRAM_TO}}
          #token: ${{secrets.TELEGRAM_TOKEN}}
          #message: |
            #${{github.event_name}} deployment failed
            #date

  lint:
    runs-on: ubuntu-18.04

    steps:
      # What is that red commit deletion tick doing there again
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: npm install
        run: npm install
      
      - name: lint
        run: npm run eslint
      
